name: Build Satis

on:
  workflow_dispatch:
  repository_dispatch:
    types: [rebuild]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: composer

      - name: Install Satis
        run: |
          composer create-project --keep-vcs --no-dev composer/satis:dev-main satis-tool \
            --no-interaction \
            --no-progress

      - name: Build Satis
        env:
          COMPOSER_AUTH: '{"github-oauth":{"github.com":"${{ secrets.SATIS_GITHUB_TOKEN }}"}}'
        run: php satis-tool/bin/satis build satis.json public --no-interaction

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
